#!/bin/sh

# Slackware build script for CMS Made Simple 1.x

# Written by Niki Kovacs <info@microlinux.fr>
#
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This script will ask you to provide values for three variables:
#
# DOMAIN is your CMS domain, e. g. example.com, microlinux.eu, etc.
#
# DOCROOT is your server's DocumentRoot directory, something like
# /srv/httpd/htdocs or /srv/httpd/vhosts.
#
# DESTDIR is the installation path under your DocumentRoot directory, something
# like example1-cmsms/htdocs, example2-cmsms/htdocs, etc.
#
# The resulting package will be named cmsmadesimple1-$DOMAIN-$VERSION, so you
# can install and run multiple CMS Made Simple instances for different domains 
# on a single server, using Apache Virtual Hosts.

PRGNAM=cmsmadesimple
VERSION=${VERSION:-1.12.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_microlinux}

ARCH=noarch

PHPUSER=apache
PHPGROUP=apache

CWD=$(pwd)
TMP=${TMP:-/tmp/microlinux}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

echo
echo "First, type in your domain. This will be something like example.com,"
echo "example.net, example.org, etc."
echo
read -p "DOMAIN [defaultdomain] : " DOMAIN
DOMAIN=${DOMAIN:-defaultdomain}
echo
echo "Next, type in the location of your server's DocumentRoot directory."
echo "Typically, this will be /srv/httpd/htdocs or /srv/httpd/vhosts."
echo
read -p "DOCROOT [/srv/httpd/htdocs] : " DOCROOT
DOCROOT=${DOCROOT:-/srv/httpd/htdocs}
echo
echo "Now, choose a destination folder for your CMS Made Simple installation."
echo "Sensible choices are cmsmadesimple/htdocs, example-cmsmadesimple/htdocs, etc."
echo
read -p "DESTDIR [cmsmadesimple/htdocs] : " DESTDIR
DESTDIR=${DESTDIR:-cmsmadesimple/htdocs}
echo
echo "DOMAIN  = $DOMAIN"
echo "DOCROOT = $DOCROOT"
echo "DESTDIR = $DESTDIR"
echo
echo "Ten seconds to bail out by hitting [Ctrl]+[C]..."
echo

sleep 10

DOWNLOAD="http://s3.amazonaws.com/cmsms/downloads/12791/$PRGNAM-$VERSION-full.tar.gz"

wget -c $DOWNLOAD

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

mkdir -p $PKG/$DOCROOT/$DESTDIR
cd $PKG/$DOCROOT/$DESTDIR
tar xvf $CWD/$PRGNAM-$VERSION-full.tar.gz

# Move documentation to an appropriate place
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
mv doc/{.[!.]*,*} $PKG/usr/doc/$PRGNAM-$VERSION
rmdir doc

# Set strong directory permissions 
chown -R $PHPUSER:$PHPGROUP $PKG/$DOCROOT/*
find $PKG/$DOCROOT/* -type d -exec chmod 0750 {} \;
find $PKG/$DOCROOT/* -type f -exec chmod 0640 {} \;

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat > $PKG/install/slack-desc <<EOF
$PRGNAM-$DOMAIN: $PRGNAM-$DOMAIN (content management application)
$PRGNAM-$DOMAIN:
$PRGNAM-$DOMAIN: CMS Made Simple, an open source content management system, allows for
$PRGNAM-$DOMAIN: faster and easier management of website content. This CMS is scalable
$PRGNAM-$DOMAIN: for small businesses to large corporations.
$PRGNAM-$DOMAIN: 
$PRGNAM-$DOMAIN:
$PRGNAM-$DOMAIN: Packaged for the [$DOMAIN] domain.
$PRGNAM-$DOMAIN:
$PRGNAM-$DOMAIN:
$PRGNAM-$DOMAIN: Package created by Niki Kovacs <info@microlinux.fr>
EOF

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$DOMAIN-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
